# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Francisco Hui
tagline:             ''
description:         'A place to reflect and capture topics of interest'
url:                 http://franciscohui.com
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]

# About/contact
author:
  name:              Francisco Hui
  url:               https://twitter.com/franciscohui

# Custom vars
version:             0.0.1
